### ISSUE TITLE
caQtDM ui screen has clipped title

### ISSUE THREAD

**Issue by prjemian** [areaDetector/ADPilatus#12]
Need more generous space for long titles in pilatusDetector.ui screen, probably go back to ADL file to fix.  The title on this example screen is clipped at both ends.

![screen](https://user-images.githubusercontent.com/2279984/39140786-4c5f6a32-46eb-11e8-8e71-7da15e24c2be.jpg)

**Comment by MarkRivers** [comment]
Are you using the file in the autoconvert directory?  If so it should not look like this because the medm file was changed to have a large title text widget in January,  Your screen shot is also missing hthe ResetModulePower widgets.

**Comment by prjemian** [comment]
You are probably right.  We are working from a beam line account which may point to older versions, perhaps even before the autoconvert directory.  I'll check for those first.  And report back.

**Comment by MarkRivers** [comment]
There were old files in the op/ui directory that did not belong there, because they were really just autoconverted files.  I have deleted them, so now there are only the op/ui/autoconvert files which fix this issue.
