### ISSUE TITLE
Driver fails to read in Tiff with wrong size

### ISSUE THREAD

**Issue by GDYendell** [areaDetector/ADPilatus#13]
I have two Pilatus detectors that, when run above a certain rate (I have been testing at 200Hz), seem to occasionally produce corrupt tiff files. The driver fails to read the file with:

```
2020/01/08 11:01:01.090 pilatusDetector::readTiff, file size incorrect =9906100, should be 9906116
```

and retries forever. It has to be Stopped to break it out, although I have seen this fail at least once and I had to restart the IOC.

I have added in some logic to only retry five times and then drop out and pass on an empty NDArray to try and figure out what is going on. I found that about ~2%~ 0.2% of frames have this problem and that they are always 16 bytes smaller than expected. I think this change will be sufficient for the particular use case, but I wonder if there is a better solution to stop this from happening at all.

@MarkRivers is this something you have seen before? I think it is only since I updated to version R2-7, but it may just be that the beamline is running it faster now. I also can't see any changes that could cause this new behaviour.

**Comment by MarkRivers** [comment]
I have not seen this, but we rarely run that fast.

Have you looked at the actual TIFF files that camserver wrote when this happens?  Are they actually 16 bytes smaller than the "normal" TIFF files?  

What model Pilatus are these, and what version of camserver?

**Comment by GDYendell** [comment]
The files are always the same `9910196` bytes.

PILATUS3 2M, S/N 24-0120 / S/N 24-0113, camserver-7.5.13-P2M / camserver-7.6.4-P2M

I am using ADCore 3-8, ADPilatus 2-7. I have tried reverting to ADCore 3-4, ADPilatus 2-5 and the problem went away, but then after switching back again, the problem was still gone. This happened once before and the problem came back after a couple of weeks.

**Comment by MarkRivers** [comment]
The Pilatus 2M is 1475 x 1679 pixels, correct?  If so then the image should be 1475*1679*4=9906100.

So in this error message it is actually the "should be" size that is incorrect, not the actual size, which is correct.
> 2020/01/08 11:01:01.090 pilatusDetector::readTiff, file size incorrect =9906100, should be 9906116

I see the problem.  It is using pImage->dataSize as the expected size of the image.  This is incorrect, because NDArray::dataSize is the actual size of the allocated buffer, which may be larger than required.  The logic needs to be changed to compute the expected size and not use pImage->dataSize.

**Comment by MarkRivers** [comment]
I have changed the code to call pImage->getInfo(&arrayInfo).  arrayInfo.totalBytes is now used as the expected size, rather than pImage->dataSize.

Please see if this works, and if it fixes the problem.

I'm not sure why you had some NDArrays in your NDArrayPool that were 16 bytes larger than the others, but this must have been what was happening.

Mark

**Comment by GDYendell** [comment]
Yep, that fixes it. Thanks, Mark!

There are a couple of other usages of `pImage->dataSize` in the same method. Should they be changed, too? Would it still be worthwhile adding the change to limit retries?

**Comment by MarkRivers** [comment]
I was not clear.  I already changed all occurrences of pImage->dataSize in that file and committed to Github.  Did you use the new master branch or make the changes yourself?

**Comment by GDYendell** [comment]
I made the change myself. I cannot see the change on master.

**Comment by MarkRivers** [comment]
My mistake, I had committed but not pushed to github.  The master branch should now be OK.

**Comment by GDYendell** [comment]
I see it. I will double-check with the latest master now.

**Comment by GDYendell** [comment]
I can confirm the problem is gone on the latest master. If I make this change on top of master it breaks again:

```
diff --git a/pilatusApp/src/pilatusDetector.cpp b/pilatusApp/src/pilatusDetector.cpp
index 439744c..7381508 100644
--- a/pilatusApp/src/pilatusDetector.cpp
+++ b/pilatusApp/src/pilatusDetector.cpp
@@ -713,7 +713,7 @@ asynStatus pilatusDetector::readTiff(const char *fileName, epicsTimeStamp *pStar
             buffer += size;
             totalSize += size;
         }
-        if (totalSize != arrayInfo.totalBytes) {
+        if (totalSize != pImage->dataSize) {
             status = asynError;
             asynPrint(this->pasynUserSelf, ASYN_TRACE_ERROR,
                 "%s::%s, file size incorrect =%lu, should be %lu\n",
```

Thanks again, Mark!

**Comment by MarkRivers** [comment]
Excellent, thanks.  I will close this issue.
