### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by ralphlange** [areaDetector/ADPilatus#21]
Found while packaging for ITER's CODAC Core System:
The repo has no LICENSE file and doesn't mention the license in the documentation.

**Comment by MarkRivers** [comment]
Added EPICS license file.

Also added LICENSE files to all 37 areaDetector repositories that did not have them.

**Comment by ralphlange** [comment]
:-)

Smart move...
But only this one and ADVimba are on my to-do-list. ADVimba is about to get a new release, right? Should I wait around?

**Comment by MarkRivers** [comment]
ADVimba R1-5 is now released.
