### ISSUE TITLE
CBFlib location is wrong

### ISSUE THREAD

**Issue by ralphlange** [areaDetector/ADPilatus#22]
https://github.com/areaDetector/ADPilatus/blob/5a649ceb3392b581a19c005db6584fde73ab6ded/pilatusApp/src/Makefile#L9
points to the former location of the CBFlib, which has been moved to ADSupport.

**Comment by MarkRivers** [comment]
Fixed, just removed that line, no longer needed since ADSupport include files are automatically found.

**Comment by ralphlange** [comment]
Thank you!
Actually, I'm not packaging ADSupport, as for Linux practically all of the third-party modules are available as system packages.
(Being on RedHat:) CBFlib is not. So, I'll package that first.
